ssh distrib-1 "cd distrib && bash /home/distrib04/distrib/setupenv.sh"
ssh distrib-2 "cd distrib && bash /home/distrib04/distrib/setupenv.sh"
ssh distrib-3 "cd distrib && bash /home/distrib04/distrib/setupenv.sh"
ssh distrib-4 "cd distrib && bash /home/distrib04/distrib/setupenv.sh"
ssh distrib-5 "cd distrib && bash /home/distrib04/distrib/setupenv.sh"